ERROR 2024-08-26 18:44:05,567 django.request Thread-1 (process_request_thread) 8880 log log.py 248 django.request log_response 10408 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 18:44:05,571 django.server Thread-1 (process_request_thread) 8880 basehttp basehttp.py 213 django.server log_message 10408 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-26 18:54:34,761 django.request Thread-1 (process_request_thread) 9088 log log.py 248 django.request log_response 15880 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 18:54:34,763 django.server Thread-1 (process_request_thread) 9088 basehttp basehttp.py 213 django.server log_message 15880 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-26 18:58:01,687 django.request Thread-2 (process_request_thread) 7220 log log.py 248 django.request log_response 15880 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 18:58:01,688 django.server Thread-2 (process_request_thread) 7220 basehttp basehttp.py 213 django.server log_message 15880 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-26 19:00:19,639 django.request Thread-2 (process_request_thread) 7220 log log.py 248 django.request log_response 15880 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 19:00:19,823 django.server Thread-2 (process_request_thread) 7220 basehttp basehttp.py 213 django.server log_message 15880 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-26 19:02:23,649 django.request Thread-3 (process_request_thread) 9504 log log.py 248 django.request log_response 15880 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 19:02:23,653 django.server Thread-3 (process_request_thread) 9504 basehttp basehttp.py 213 django.server log_message 15880 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-26 19:05:28,260 django.request Thread-1 (process_request_thread) 17688 log log.py 248 django.request log_response 6104 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 19:05:31,000 django.server Thread-1 (process_request_thread) 17688 basehttp basehttp.py 213 django.server log_message 6104 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-26 21:20:28,715 django.request Thread-1 (process_request_thread) 11712 log log.py 248 django.request log_response 15880 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 21:20:30,299 django.server Thread-1 (process_request_thread) 11712 basehttp basehttp.py 213 django.server log_message 15880 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-26 21:23:13,440 django.request Thread-2 (process_request_thread) 12812 log log.py 248 django.request log_response 15880 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 21:23:14,361 django.server Thread-2 (process_request_thread) 12812 basehttp basehttp.py 213 django.server log_message 15880 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-26 21:30:20,979 django.request Thread-1 (process_request_thread) 7888 log log.py 248 django.request log_response 7224 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 21:30:21,253 django.server Thread-1 (process_request_thread) 7888 basehttp basehttp.py 213 django.server log_message 7224 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-26 21:32:22,263 django.request Thread-1 (process_request_thread) 7996 log log.py 248 django.request log_response 18076 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 21:32:23,187 django.server Thread-1 (process_request_thread) 7996 basehttp basehttp.py 213 django.server log_message 18076 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-26 21:47:48,135 django.request Thread-1 (process_request_thread) 7152 log log.py 248 django.request log_response 15128 Internal Server Error: /analysis/upload/
ERROR 2024-08-26 21:47:48,142 django.server Thread-1 (process_request_thread) 7152 basehttp basehttp.py 213 django.server log_message 15128 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-27 18:49:36,870 django.request Thread-1 (process_request_thread) 15128 log log.py 248 django.request log_response 10856 Internal Server Error: /analysis/upload/
ERROR 2024-08-27 18:49:36,873 django.server Thread-1 (process_request_thread) 15128 basehttp basehttp.py 213 django.server log_message 10856 "POST /analysis/upload/ HTTP/1.1" 500 34
WARNING 2024-08-27 18:50:46,255 django.request Thread-2 (process_request_thread) 11412 log log.py 248 django.request log_response 10856 Not Found: /analysis/urls/
WARNING 2024-08-27 18:50:46,332 django.server Thread-2 (process_request_thread) 11412 basehttp basehttp.py 213 django.server log_message 10856 "POST /analysis/urls/ HTTP/1.1" 404 2344
WARNING 2024-08-27 18:51:10,934 django.request Thread-3 (process_request_thread) 6688 log log.py 248 django.request log_response 10856 Not Found: /analysis/views/
WARNING 2024-08-27 18:51:11,031 django.server Thread-3 (process_request_thread) 6688 basehttp basehttp.py 213 django.server log_message 10856 "POST /analysis/views/ HTTP/1.1" 404 2347
WARNING 2024-08-27 18:51:36,488 django.request Thread-4 (process_request_thread) 16860 log log.py 248 django.request log_response 10856 Not Found: /analysis/
WARNING 2024-08-27 18:51:36,596 django.server Thread-4 (process_request_thread) 16860 basehttp basehttp.py 213 django.server log_message 10856 "POST /analysis/ HTTP/1.1" 404 2329
ERROR 2024-08-27 18:52:54,011 django.request Thread-5 (process_request_thread) 7004 log log.py 248 django.request log_response 10856 Internal Server Error: /analysis/upload
Traceback (most recent call last):
  File "C:\Users\isabe\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\isabe\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\isabe\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\isabe\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/analysis/upload/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2024-08-27 18:52:54,013 django.server Thread-5 (process_request_thread) 7004 basehttp basehttp.py 213 django.server log_message 10856 "POST /analysis/upload HTTP/1.1" 500 74362
ERROR 2024-08-27 19:01:28,662 django.request Thread-1 (process_request_thread) 8852 log log.py 248 django.request log_response 7396 Internal Server Error: /analysis/upload/
ERROR 2024-08-27 19:01:28,666 django.server Thread-1 (process_request_thread) 8852 basehttp basehttp.py 213 django.server log_message 7396 "POST /analysis/upload/ HTTP/1.1" 500 34
WARNING 2024-08-27 19:01:29,612 django.request Thread-1 (process_request_thread) 8852 log log.py 248 django.request log_response 7396 Not Found: /favicon.ico
WARNING 2024-08-27 19:01:29,616 django.server Thread-1 (process_request_thread) 8852 basehttp basehttp.py 213 django.server log_message 7396 "GET /favicon.ico HTTP/1.1" 404 2217
ERROR 2024-08-27 19:02:11,497 django.request Thread-3 (process_request_thread) 1156 log log.py 248 django.request log_response 7396 Internal Server Error: /analysis/upload/
ERROR 2024-08-27 19:02:11,505 django.server Thread-3 (process_request_thread) 1156 basehttp basehttp.py 213 django.server log_message 7396 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-27 19:06:23,784 django.request Thread-5 (process_request_thread) 14616 log log.py 248 django.request log_response 7396 Internal Server Error: /analysis/upload/
ERROR 2024-08-27 19:06:23,788 django.server Thread-5 (process_request_thread) 14616 basehttp basehttp.py 213 django.server log_message 7396 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-27 19:06:26,209 django.request Thread-7 (process_request_thread) 9552 log log.py 248 django.request log_response 7396 Internal Server Error: /analysis/upload/
ERROR 2024-08-27 19:06:26,211 django.server Thread-7 (process_request_thread) 9552 basehttp basehttp.py 213 django.server log_message 7396 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-27 19:08:01,047 django.request Thread-9 (process_request_thread) 2104 log log.py 248 django.request log_response 7396 Internal Server Error: /analysis/upload/
ERROR 2024-08-27 19:08:01,048 django.server Thread-9 (process_request_thread) 2104 basehttp basehttp.py 213 django.server log_message 7396 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-27 20:34:05,599 django.request Thread-1 (process_request_thread) 16524 log log.py 248 django.request log_response 15580 Internal Server Error: /analysis/upload/
ERROR 2024-08-27 20:34:05,603 django.server Thread-1 (process_request_thread) 16524 basehttp basehttp.py 213 django.server log_message 15580 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-27 20:51:23,644 django.request Thread-2 (process_request_thread) 14936 log log.py 248 django.request log_response 15580 Internal Server Error: /analysis/upload/
ERROR 2024-08-27 20:51:23,644 django.server Thread-2 (process_request_thread) 14936 basehttp basehttp.py 213 django.server log_message 15580 "POST /analysis/upload/ HTTP/1.1" 500 34
ERROR 2024-08-27 20:57:30,055 django.request Thread-3 (process_request_thread) 11400 log log.py 248 django.request log_response 15580 Internal Server Error: /analysis/upload/
ERROR 2024-08-27 20:57:30,057 django.server Thread-3 (process_request_thread) 11400 basehttp basehttp.py 213 django.server log_message 15580 "POST /analysis/upload/ HTTP/1.1" 500 34
WARNING 2024-08-27 21:06:13,997 django.request Thread-1 (process_request_thread) 15708 log log.py 248 django.request log_response 11844 Bad Request: /analysis/upload/
WARNING 2024-08-27 21:06:13,999 django.server Thread-1 (process_request_thread) 15708 basehttp basehttp.py 213 django.server log_message 11844 "POST /analysis/upload/ HTTP/1.1" 400 65
WARNING 2024-08-27 21:09:21,442 django.request Thread-1 (process_request_thread) 15600 log log.py 248 django.request log_response 4932 Bad Request: /analysis/upload/
WARNING 2024-08-27 21:09:21,442 django.server Thread-1 (process_request_thread) 15600 basehttp basehttp.py 213 django.server log_message 4932 "POST /analysis/upload/ HTTP/1.1" 400 65
WARNING 2024-08-27 21:11:50,489 django.request Thread-2 (process_request_thread) 13456 log log.py 248 django.request log_response 4932 Bad Request: /analysis/upload/
WARNING 2024-08-27 21:11:50,491 django.server Thread-2 (process_request_thread) 13456 basehttp basehttp.py 213 django.server log_message 4932 "POST /analysis/upload/ HTTP/1.1" 400 65
WARNING 2024-08-27 21:14:21,245 django.request Thread-1 (process_request_thread) 11780 log log.py 248 django.request log_response 10600 Bad Request: /analysis/upload/
WARNING 2024-08-27 21:14:21,261 django.server Thread-1 (process_request_thread) 11780 basehttp basehttp.py 213 django.server log_message 10600 "POST /analysis/upload/ HTTP/1.1" 400 65
WARNING 2024-08-27 21:24:14,380 django.request Thread-1 (process_request_thread) 15100 log log.py 248 django.request log_response 1588 Bad Request: /analysis/upload/
WARNING 2024-08-27 21:24:14,382 django.server Thread-1 (process_request_thread) 15100 basehttp basehttp.py 213 django.server log_message 1588 "POST /analysis/upload/ HTTP/1.1" 400 65
